Store_Project/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Store_Project.Data;
using Store_Project.Models;

namespace Store_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TagsController : Controller
    {
        private readonly Store_ProjectContext _context;

        public TagsController(Store_ProjectContext context)
        {
            _context = context;
        }


        private void SetPizzaListItemsAsync(int[] pizzasId=null)
        {
           ViewBag.pizzas = new MultiSelectList(_context.Pizza, nameof(Pizza.Id), nameof(Pizza.Name), pizzasId);
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
            IOrderedQueryable<Tag> q = from t in _context.Tag.Include(t => t.Pizza_tag)
                                       orderby t.Pizza_tag.Count descending
                                       select t;
            return View(await q.ToListAsync());
        }

        // GET: Tags/Search
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Search(string searchquery)
        {
            IOrderedQueryable<Tag> q = from t in _context.Tag.Include(t => t.Pizza_tag)
                                       where
                                       t.Name.Contains(searchquery) || (searchquery == null)
                                       orderby t.Pizza_tag.Count descending
                                       select t;

            return Json(await q.ToListAsync());
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tag.Include(t => t.Pizza_tag)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            SetPizzaListItemsAsync();
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Color")] Tag tag, int[] Pizza_tag)
        {
            if (ModelState.IsValid)
            {
                tag.Pizza_tag = new List<Pizza>();
                tag.Pizza_tag.AddRange(_context.Pizza.Where(x => Pizza_tag.Contains(x.Id)));

                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tag.Include(t => t.Pizza_tag).FirstOrDefaultAsync(e => e.Id == id);
            int[] pizzasId= tag.Pizza_tag.Select(p => p.Id).ToArray();
            SetPizzaListItemsAsync(pizzasId);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Color")] Tag tag, int[] Pizza_tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Remove existing pizzas
                    Tag tt = await _context.Tag.Include(t => t.Pizza_tag).SingleOrDefaultAsync(t => t.Id == id);
                    if (tt != null)
                    {
                        foreach (Pizza p in tt.Pizza_tag.ToList())
                        {
                            tt.Pizza_tag.Remove(p);
                        }
                        await _context.SaveChangesAsync();
                    }
                    _context.Entry(tt).State = EntityState.Detached;

                    // adding new tags selected
                    tag.Pizza_tag = new List<Pizza>();
                    tag.Pizza_tag.AddRange(_context.Pizza.Where(p => Pizza_tag.Contains(p.Id)));




                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }


        // Get: Tags/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var tag = await _context.Tag.FindAsync(id);
            _context.Tag.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
            return _context.Tag.Any(e => e.Id == id);
        }
    }
}

Store_Project/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Store_Project.Data;
using Store_Project.Models;

namespace Store_Project.Controllers
{
    public class UsersController : Controller
    {
        private readonly Store_ProjectContext _context;

        public UsersController(Store_ProjectContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Logout()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login");
        }

        // GET: Users/Register
        public IActionResult Register()
        {
            return View();
        }

        public IActionResult AccessDenied()  
        {
            return View();
        }


        // POST: Users/Register
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("Id,Username,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                var q = _context.User.FirstOrDefault(u => u.Username == user.Username);

                if (q == null)
                {
                    user.Type = User_type.Client;
                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    var u = _context.User.FirstOrDefault(u => u.Username == user.Username && u.Password == user.Password);

                    Signin(u);

                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "unable to comply; username already exist";
                }

            }
            return View(user);
        }

        //GET: Users/RegisterAdmin
        [Authorize(Roles = "Admin")]
        public IActionResult RegisterAdmin()
        {
            return View();
        }

        // POST: Users/RegisterAdmin
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RegisterAdmin([Bind("Id,Username,Password,Type")] User user)
        {
            if (ModelState.IsValid)
            {
                // Check if the user already exists
                var userExists = _context.User.FirstOrDefault(u => u.Username == user.Username);

                if (userExists == null)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "unable to comply; username already exist";
                }
            }
            return View(user);
        }

        // GET: Users/Login
        public IActionResult Login()
        {
            return View();
        }

        // POST: Users/Login
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Id,Username,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                var q = from u in _context.User
                        where u.Username == user.Username && u.Password == user.Password
                        select u;


                if (q.Count() > 0)
                {
                   
                    Signin(q.First());
                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "unable to comply; username /password are incorrect";
                }

            }
            return View(user);
        }

        private async void Signin(User account)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, account.Username),
                new Claim(ClaimTypes.Role, account.Type.ToString()),
            };

            var claimIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(15)
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimIdentity),
                authProperties);
        }



        // GET: Users
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Search(string searchquery)
        {
            IOrderedQueryable<User> q = from u in _context.User
                                        where
                                        u.Username.Contains(searchquery) || (searchquery == null)
                                        orderby u.Id ascending
                                        select u;

            return Json(await q.ToListAsync());
        }

        // GET: Users/ChangePassword
        [Authorize]
        public async Task<IActionResult> ChangePassword()
        {
            return View("ChangePassword", await _context.User.FirstOrDefaultAsync(u => u.Username.Equals(this.User.Identity.Name)));
        }

        // POST: Users/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> ChangePassword(string oldpass, string newpass)
        {
            User curr_user = await _context.User.FirstOrDefaultAsync(u => u.Username.Equals(this.User.Identity.Name));
            curr_user.Password = newpass;
            _context.Update(curr_user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home");
        }

        /*
        // GET: Users/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        */

        /*
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,Type")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }
        */

        private SelectList GetUserTypes()
        {
            var typeEnum = from User_type ut in Enum.GetValues(typeof(User_type))
                           select new
                           {
                               ID = (int)ut,
                               Name = ut.ToString()
                           };
            return new SelectList(typeEnum, "ID", "Name");

        }
        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            ViewBag.UserTypes = GetUserTypes();
            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,Type")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Check if the username already exists
                    User userExists = _context.User.FirstOrDefault(u => (u.Username == user.Username && u.Id != user.Id));

                    if (userExists == null)
                    {
                        _context.Update(user);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else

Store_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/PizzaCard.css" />
    <link href='~/css/site.css?version=1' rel='stylesheet'/>

</head>
<body dir="ltr">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">
                    @*<img src="~/Pictures/MonAmour.jpg" class="logo" width="50" />*@
                    <canvas id="logoCanvas"  width="90" height="50"> your browser does not support the HTML canvas tag.</canvas>
                    <br />
                    <b class="active price-shadow">Mon Amour</b>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-pills btn-outline-danger">
                            <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Pizzas" asp-action="Menu">Menu</a>
                        </li>


                        @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                        {
                            @if (this.User.IsInRole("Admin"))
                            {
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Pizzas" asp-action="index">Pizzas</a>
                                </li>
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Tags" asp-action="index">Tags</a>
                                </li>
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Toppings" asp-action="index">Toppings</a>
                                </li>
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Branches" asp-action="index">Branches</a>
                                </li>
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Orders" asp-action="index">Orders</a>
                                </li>
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                </li>
                            }

                            // non admin user
                            else
                            {
                                <li class="nav-pills btn-outline-danger">
                                    <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Orders" asp-action="MyOrders">Past Orders</a>
                                </li>
                            }

                            <li class="nav-pills btn-outline-danger">
                                <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Users" asp-action="ChangePassword">Change Password</a>
                            </li>
                            <li class="nav-pills btn-outline-danger">
                                <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item mr-auto">
                                <div class="nav-link text-light connected_as"> Hello <b>@Context.User.Identities.FirstOrDefault().Name</b></div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-pills btn-outline-danger">
                                <a class="nav-link text-light admin_menu" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Mon Amour Pizza
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


    <script src="~/lib/forModal/popper.min.js"></script>
    <script src="~/lib/forModal/bootstrap.min.js"></script>

    <script src="~/js/Canvas.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Store_Project/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>